# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactcliexample' do
# uhutu_autonotebegin_react_note_plug_rn_voip
pod 'RongCloudIM/IMLib', '2.8.8'
pod 'RongCloudIM/IMKit', '2.8.8'
pod 'RongCloudIM/CallLib', '2.8.8'
pod 'RongCloudIM/CallKit', '2.8.8'
# uhutu_autonoteend_react_note_plug_rn_voip
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactcliexample



  target 'reactcliexampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactcliexample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactcliexample-tvOS

  target 'reactcliexample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
